# Generated by Django 3.0.3 on 2020-05-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200517_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='entries.Article'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='entries.Group'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='commentary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
