# Generated by Django 3.0.3 on 2020-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20200517_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='commentary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
