# Generated by Django 3.0.3 on 2020-05-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20200517_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='entries.Language'),
            preserve_default=False,
        ),
    ]
