# Generated by Django 3.0.3 on 2020-05-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_translation_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='word',
            new_name='name',
        ),
    ]
