# Generated by Django 3.0.3 on 2020-05-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20200520_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.AddField(
            model_name='entry',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='entries', to='entries.Group'),
        ),
    ]
