# Generated by Django 3.0.3 on 2020-05-20 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0007_auto_20200520_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Topic',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='groups',
        ),
        migrations.AddField(
            model_name='entry',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='entries', to='entries.Topic'),
        ),
    ]
