# Generated by Django 3.0.3 on 2020-05-20 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0008_auto_20200520_1329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('name', 'language', 'user')},
        ),
    ]
