# Generated by Django 3.0.3 on 2020-05-20 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0009_auto_20200520_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('name', 'language', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('user', 'abbreviation')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'language', 'user')},
        ),
    ]
