# Generated by Django 3.0.3 on 2020-05-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20200520_1510'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
    ]
