# Generated by Django 3.0.3 on 2020-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20200520_1517'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('name', 'language', 'user'), name='constraint - unique article'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('name', 'language', 'user'), name='constraint - unique entry'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('abbreviation', 'user'), name='constraint - unique language'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('name', 'language', 'user'), name='constraint - unique topic'),
        ),
    ]
