# Generated by Django 3.0.3 on 2020-05-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_auto_20200520_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='entries.Article'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='entries.Language'),
        ),
    ]
