# Generated by Django 3.0.3 on 2020-05-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_auto_20200520_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['content']},
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='commentary',
            new_name='note',
        ),
    ]
