# Generated by Django 3.0.3 on 2020-05-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_auto_20200521_1651'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='constraint - unique entry',
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('name', 'language', 'user', 'article'), name='constraint - unique entry'),
        ),
    ]
