# Generated by Django 3.0.3 on 2020-05-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_auto_20200521_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topics',
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='entries.Topic'),
        ),
    ]
