# Generated by Django 3.0.3 on 2020-05-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_translation_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('entry', 'content'), name='constraint - unique translation'),
        ),
    ]
