# Generated by Django 3.0.3 on 2020-06-09 13:48

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0018_auto_20200522_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': [django.db.models.functions.text.Lower('content')]},
        ),
    ]
